# Generated by Django 4.2.4 on 2023-08-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.EmailField(max_length=254)),
                ('itag', models.CharField(max_length=200)),
            ],
        ),
    ]
