# Generated by Django 4.2.4 on 2023-08-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
