# Generated by Django 4.2.4 on 2023-08-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='profile.png', upload_to='images/'),
        ),
    ]
